/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications to this file will be overwritten the next time
 * the TypeGen command is executed.
 * ---------------------------------------------------------------------------------
 */

import type { SanityImageCrop, SanityImageHotspot } from '@sanity/image-url'

export type { SanityImageCrop, SanityImageHotspot }

export type SanityImageAsset = {
  _id: string
  url: string
  metadata?: {
    lqip?: string
    dimensions?: {
      width: number
      height: number
      aspectRatio: number
    }
  }
}

export type SanityImageObject = {
  asset?: SanityImageAsset
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  caption?: string
}

export type SanitySlug = {
  _type: 'slug'
  current: string
}

export type SeoFields = {
  metaTitle?: string
  metaDescription?: string
  openGraphTitle?: string
  openGraphDescription?: string
  openGraphImage?: {
    asset?: { url?: string }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
  }
  canonicalUrl?: string
  noIndex?: boolean
  schemaMarkup?: string
}

export type AuthorDocument = {
  _id: string
  _type: 'author'
  name?: string
  slug?: SanitySlug
  bio?: string
  avatar?: {
    asset?: { _id?: string; url?: string; metadata?: { lqip?: string } }
    alt?: string
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
  }
  twitterHandle?: string
  linkedInUrl?: string
}

export type CategoryDocument = {
  _id: string
  _type: 'category'
  title?: string
  slug?: SanitySlug
  description?: string
}

export type BlockContentType = Array<
  | {
      _type: 'block'
      _key: string
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
      children?: Array<{
        _type: 'span'
        _key: string
        text?: string
        marks?: string[]
      }>
      markDefs?: Array<{
        _key: string
        _type: 'link'
        href?: string
        blank?: boolean
      }>
    }
  | {
      _type: 'image'
      _key: string
      asset?: SanityImageAsset
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    }
  | {
      _type: 'codeBlock'
      _key: string
      language?: string
      filename?: string
      code?: string
    }
  | {
      _type: 'callout'
      _key: string
      type?: 'info' | 'warning' | 'tip'
      text?: string
    }
  | {
      _type: 'table'
      _key: string
      rows?: Array<{
        _key: string
        cells?: string[]
      }>
    }
>

export type BlogPostDocument = {
  _id: string
  _type: 'blogPost'
  title?: string
  slug?: SanitySlug
  status?: 'draft' | 'published' | 'archived'
  author?: AuthorDocument
  category?: CategoryDocument
  tags?: string[]
  excerpt?: string
  publishedAt?: string
  mainImage?: {
    asset?: SanityImageAsset
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  }
  body?: BlockContentType
  seo?: SeoFields
  readingTime?: number
  featured?: boolean
  relatedPosts?: Array<{
    _id: string
    title?: string
    slug?: SanitySlug
    excerpt?: string
    publishedAt?: string
    mainImage?: {
      asset?: SanityImageAsset
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    }
  }>
}

export type BlogListItem = Pick<
  BlogPostDocument,
  | '_id'
  | 'title'
  | 'slug'
  | 'excerpt'
  | 'publishedAt'
  | 'category'
  | 'tags'
  | 'readingTime'
  | 'featured'
  | 'mainImage'
  | 'author'
>
