/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HumanReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "human";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "published" | "coming_soon";
  topic?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  excerpt?: string;
  body?: BlockContent;
  authors?: Array<
    {
      _key: string;
    } & HumanReference
  >;
  audience?: string;
  publishedAt?: string;
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tags?: Array<string>;
  featured?: boolean;
  formConfig?: {
    submitButtonText?: string;
    confirmationMessage?: string;
    trustIndicators?: Array<string>;
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphTitle?: string;
  openGraphDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
  primaryKeyword?: string;
  secondaryKeywords?: Array<string>;
  lsiKeywords?: Array<string>;
  schemaMarkup?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | {
      type?: "info" | "warning" | "tip";
      text?: string;
      _type: "callout";
      _key: string;
    }
  | {
      rows?: Array<{
        cells?: Array<string>;
        _type: "tableRow";
        _key: string;
      }>;
      _type: "table";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Brochure = {
  _id: string;
  _type: "brochure";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "published" | "coming_soon";
  description?: string;
  publishedAt?: string;
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Whitepaper = {
  _id: string;
  _type: "whitepaper";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "published" | "coming_soon";
  excerpt?: string;
  abstract?: string;
  authors?: Array<
    {
      _key: string;
    } & HumanReference
  >;
  audience?: string;
  publishedAt?: string;
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  gated?: boolean;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tags?: Array<string>;
  featured?: boolean;
  seo?: Seo;
};

export type CompetitorPage = {
  _id: string;
  _type: "competitorPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  competitorName?: string;
  order?: number;
  heroHeading?: string;
  heroSubtitle?: string;
  aboutHeading?: string;
  aboutBody?: string;
  aboutTrustBadges?: Array<string>;
  awardBadges?: Array<{
    label?: string;
    sub?: string;
    _key: string;
  }>;
  comparisonCategories?: Array<{
    title?: string;
    rows?: Array<{
      feature?: string;
      us?: boolean;
      them?: "yes" | "no" | "partial";
      _key: string;
    }>;
    _key: string;
  }>;
  switchSteps?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  rightChoiceHeading?: string;
  rightChoiceItems?: Array<string>;
  ctaHeading?: string;
  ctaDescription?: string;
  seo?: Seo;
};

export type SolutionPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "solutionPage";
};

export type SolutionPage = {
  _id: string;
  _type: "solutionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navCategory?: "BY CARE TYPE" | "BY ROLE" | "BY STAGE";
  order?: number;
  heroHeading?: string;
  heroSubtitle?: string;
  navSubtitle?: string;
  whoIsThisFor?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyBenefits?: Array<string>;
  howWeSupport?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whatYouGet?: Array<string>;
  isThisRightForYou?: Array<string>;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionPageReference
  >;
  seo?: Seo;
};

export type JobListing = {
  _id: string;
  _type: "jobListing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  isOpen?: boolean;
  order?: number;
  tags?: Array<{
    icon?: "dollar" | "home" | "trending" | "users" | "zap" | "heart" | "map";
    label?: string;
    _type: "jobTag";
    _key: string;
  }>;
  summary?: string;
  sections?: Array<{
    heading?: string;
    layout?: "prose" | "list" | "two-col" | "inline-list";
    body?: string;
    items?: Array<string>;
    col1Heading?: string;
    col1Items?: Array<string>;
    col2Heading?: string;
    col2Items?: Array<string>;
    _type: "jobSection";
    _key: string;
  }>;
  contactEmail?: string;
  contactName?: string;
};

export type PricingPlan = {
  _id: string;
  _type: "pricingPlan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: Slug;
  order?: number;
  label?: string;
  tagline?: string;
  staffRange?: string;
  badge?: string;
  accentColor?: string;
  bestFor?: string;
  whatYouNeed?: string;
  automationHeading?: string;
  automationBody?: string;
  commercial?: Array<string>;
  supports?: Array<string>;
  cta?: string;
};

export type ReleaseNote = {
  _id: string;
  _type: "releaseNote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  releaseDate?: string;
  releaseType?: "major" | "minor" | "patch";
  changes?: Array<{
    title?: string;
    description?: BlockContent;
    category?: Array<string>;
    _type: "changeItem";
    _key: string;
  }>;
};
export type ReleaseNoteChange = NonNullable<ReleaseNote["changes"]>[number];

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
  isVisible?: boolean;
};

export type CapabilityPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "capabilityPage";
};

export type CapabilityPage = {
  _id: string;
  _type: "capabilityPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navGroup?:
    | "Workforce"
    | "Participant & Care"
    | "Finance"
    | "Operational Intelligence";
  order?: number;
  heroHeading?: string;
  heroSubtitle?: string;
  navSubtitle?: string;
  problemStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whatMattersMost?: Array<string>;
  howWeSolveThis?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whatYouGet?: Array<string>;
  isThisRightForYou?: Array<string>;
  relatedCapabilities?: Array<
    {
      _key: string;
    } & CapabilityPageReference
  >;
  seo?: Seo;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "published" | "archived";
  authors?: Array<
    {
      _key: string;
    } & HumanReference
  >;
  category?: CategoryReference;
  tags?: Array<string>;
  excerpt?: string;
  publishedAt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  body?: BlockContent;
  seo?: Seo;
  readingTime?: number;
  featured?: boolean;
  relatedPosts?: Array<
    {
      _key: string;
    } & BlogPostReference
  >;
  cta?: {
    variant?: "buttons" | "subscribe";
    heading?: string;
    body?: string;
    primaryLabel?: string;
    primaryUrl?: string;
    secondaryLabel?: string;
    secondaryUrl?: string;
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Human = {
  _id: string;
  _type: "human";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  department?:
    | "Leadership"
    | "Engineering"
    | "Product"
    | "Design"
    | "Sales"
    | "Marketing"
    | "Operations"
    | "Customer Success";
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkedInUrl?: string;
  twitterHandle?: string;
  githubHandle?: string;
  websiteUrl?: string;
  order?: number;
  showInTeam?: boolean;
  isBlogAuthor?: boolean;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HumanReference
  | SanityFileAssetReference
  | SanityImageAssetReference
  | Guide
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | BlockContent
  | Slug
  | Brochure
  | Whitepaper
  | CompetitorPage
  | SolutionPageReference
  | SolutionPage
  | JobListing
  | PricingPlan
  | ReleaseNote
  | ClientLogo
  | CapabilityPageReference
  | CapabilityPage
  | CategoryReference
  | BlogPostReference
  | BlogPost
  | Category
  | Human
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
