import image1 from "../assets/blog1.webp";
import image2 from "../assets/blog2.webp";
import image3 from "../assets/blog3.webp";
import image4 from "../assets/image1.webp";
import blog5 from "../assets/Blog5Image3.webp";
import blog6 from "../assets/expo-canberra1.webp";
import authorImage from "../assets/BELLE BAI - MARKETING EXECUTIVE.webp";
import blog7 from "../assets/Why Manual Rostering Is Costing You More Than You Think.webp";
import blog8 from "../assets/Beyond Compliance_ How TesseractApps NDIS Software Elevates Care Quality and Staff Experience.webp";
import blog9 from "../assets/Cover page for Top 3 Compliance Myths Busted-DESKTOP-VQ2C97V.webp";
import blog10 from "../assets/Cover page for Avoid These Common Payroll Pitfalls A Guide for NDIS Provider.webp";
import Blog11 from "../assets/MelbourneExpo.webp";
import blog13 from "../assets/Why NDIS Providers Fail Compliance Audits in 2026 _ How to Fix It.webp";
// Thumbnail variants for blog card images (generated by scripts/gen-home-thumbs.mjs)
import image1Thumb from "../assets/thumbs/blog1-thumb.webp";
import image2Thumb from "../assets/thumbs/blog2-thumb.webp";
import image3Thumb from "../assets/thumbs/blog3-thumb.webp";
import blog5Thumb from "../assets/thumbs/Blog5Image3-thumb.webp";
import blog6Thumb from "../assets/thumbs/expo-canberra1-thumb.webp";
import Blog11Thumb from "../assets/thumbs/MelbourneExpo-thumb.webp";
import authorImageThumb from "../assets/thumbs/author-belle-thumb.webp";

export const ourBlogDummyData = [
  {
    id: 1,
    slug: "/protecting-participant-data",
    title:
      "Protecting Participant Data: Why Security Matters for NDIS and Care Providers",
    description: ` Every day, disability support and aged care providers collect
            sensitive information — including health records, personal details,
            and care plans — that participants trust us to protect. Strong data
            security isn't a luxury; it's essential for compliance, service
            continuity, and, most importantly, client trust.`,
    image: image1,
    thumbnail: image1Thumb,
    date: "2025-06-01",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 2,
    slug: "/future-proofing-disability-services",
    title:
      "Future-Proofing Disability Services: Why NDIS Providers Need Smarter Systems Now",
    description: `Australia’s NDIS (National Disability Insurance Scheme) is evolving at pace. By March 2025, the scheme supported over 717,000 active participants — a 3.5% increase in just one quarter. This rapid expansion creates significant operational, compliance, and workforce challenges for NDIS providers.`,
    image: image2,
    thumbnail: image2Thumb,
    date: "2025-06-12",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },

  {
    id: 3,
    slug: "/hidden-costs-workforce-management",
    title: "The Hidden Costs of Poor Workforce Management for NDIS Providers",
    description: `NDIS service providers rely on having their operations staffed 
    properly. But too many organisations don’t realize how much bad workforce management 
    can rip into their bottom line. It’s easy to see where the money is being spent in 
    the form of staffing hours, but the hidden costs associated with overtime, absence, 
    compliance, and the negative impact on reputation are costing the providers out of 
    
            `,
    image: image4,
    date: "2025-07-28",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 4,
    slug: "/sydney-disability-workability-expo-2025",
    title:
      "Unforgettable Moments at the Disability & WorkAbility Sydney Expo 2025",
    description: `On August 8th - 9th, 2025, the TesseractApps team proudly participated in 
    the Sydney Disability & WorkAbility Expo, an event filled with connection, innovation, 
    and a shared commitment to the NDIS community. Those two days brought unforgettable 
    moments as we engaged directly with NDIS providers, support coordinators, participants, 
    and industry leaders, all dedicated to improving `,
    image: blog5,
    thumbnail: blog5Thumb,
    date: "2025-08-13",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["Events"],
  },
  {
    id: 5,
    slug: "/canberra-ndis-expo",
    title: "TesseractApps Connects with Canberra's NDIS Community at the Expo",
    description: `As a proud Canberra-based company, TesseractApps was thrilled to
            participate in the recent Canberra NDIS Expo, connecting with local
            providers, allied health professionals, and community organisations.
            The event was an invaluable opportunity to engage directly with the
            people shaping the future of care in our city.`,
    image: blog6,
    thumbnail: blog6Thumb,
    date: "2025-09-15",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["Events"],
  },
  {
    id: 6,
    slug: "/beyond-compliance-care-quality",
    title:
      "Beyond Compliance: How TesseractApps NDIS Software Elevates Care Quality and Staff Experience",
    description: `NDIS providers face strict compliance requirements while working to
            deliver quality care. TesseractApps NDIS software helps you reduce
            administration, improve staff experience, and meet compliance
            standards without losing focus on participants.
            `,
    image: blog8,
    date: "2025-09-16",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 7,
    slug: "/manual-rostering-hidden-costs",
    title: "Why Manual Rostering Is Costing You More Than You Think",
    description: `Many NDIS providers still build rosters by hand — using
            spreadsheets, whiteboards or group chats. It feels simple and
            "free". But the hidden costs add up fast. Every week, managers lose
            hours fixing mistakes. Shifts get double-booked. Overtime blows out
            budgets. Simple slip-ups mean under-claimed hours or overpayments.
            `,
    image: blog7,
    date: "2025-09-25",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 8,
    slug: "/future-proof-ndis-organisation-2025",
    title:
      "Future-Proof Your NDIS Organisation: Strategies for 2025 and Beyond",
    description: `The NDIS landscape is evolving rapidly. With regulatory changes and rising expectations from participants in 2025 and beyond, providers need smarter, more sustainable ways to operate. Future-proofing your organisation means enhancing compliance, streamlining operations, empowering your workforce, and delivering consistently high-quality care.
            `,
    image: image3,
    thumbnail: image3Thumb,
    date: "2025-10-22",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 9,
    slug: "/top-3-compliance-myths-busted",
    title: "Top 3 Compliance Myths Busted",
    description: `Compliance is one of the biggest concerns for NDIS providers. Many
            organisations worry about audits, documentation gaps, and the
            complexity of staying “NDIS-ready.” But the truth is, much of this
            fear comes from misunderstanding what compliance really involves.
            `,
    image: blog9,
    date: "2025-11-11",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 10,
    slug: "/common-payroll-pitfalls-ndis",
    title: "Avoid These Common Payroll Pitfalls: A Guide for NDIS Provider",
    description: `Payroll management is essential for NDIS providers, but even minor errors can create compliance risks, financial losses, and staff dissatisfaction. Understanding and addressing common payroll pitfalls ensures smooth operations, accurate reporting, and happier employees.

            `,
    image: blog10,
    date: "2025-11-11",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
  {
    id: 11,
    slug: "/melbourne-expo-2025",
    title:
      "TesseractApps at the Melbourne Expo 2025 Driving Smarter NDIS Operations",
    description: `TesseractApps was proud to showcase our NDIS management platform at
            the Melbourne Expo 2025, connecting with providers across Victoria
            to demonstrate how technology can simplify compliance, reduce
            administrative workload, and improve participant outcomes.`,
    image: Blog11,
    thumbnail: Blog11Thumb,
    date: "2025-12-04",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["Events"],
  },
  {
    id: 12,
    slug: "/ndis-compliance-audit-failures-2026",
    title: "Why NDIS Providers Fail Compliance Audits in 2026 | How to Fix It",
    description: `NDIS compliance audits are not failing providers because of poor
            care delivery. They fail because providers cannot demonstrate
            compliance with evidence. Learn about the common audit failures
            and how to fix them.`,
    image: blog13,
    date: "2026-01-20",
    author: "Belle Bai",
    authorImage: authorImage,
    authorImageThumb: authorImageThumb,
    comments: 0,
    categories: ["NDIS"],
  },
];

